### ISSUE TITLE
As a visitor I can view the program schedule

### ISSUE THREAD

**Issue by KatkaChee** [con2/kompassi#309]
Standard "old" style, like Tracon

**Comment by japsu** [comment]
Initial version of Program Guide v2 Light implemented by @japsu and v2 Embedded by Knome

[Docs](https://outline.con2.fi/doc/program-v2-bub1j6J2Li)
[Live demo of v2 Light](https://v2.kompassi.eu/events/solmukohta2024/program?event=solmukohta)
[Live demo of v2 Embedded](https://wp.ropecon.fi/opas)

Further development via more specific improvement tasks.
