### ISSUE TITLE
Paikkala ticket constraint missing row

### ISSUE THREAD

**Issue by Aketzu** [con2/kompassi#313]
Should `"paikkala_ticket_program_id_zone_id_number_b25cbd95_uniq" UNIQUE CONSTRAINT, btree (program_id, zone_id, number)` also include `row`?
Ref https://github.com/kcsry/paikkala/blob/93b8b98c99f31d4dbc4bfa703afd77d8df7f66d8/paikkala/models/tickets.py#L44

Case Shumicon Pääsali. There are only row marking but the seats itself are not numbered. Thus CSV data like:
```csv
zone,row,start,end
Pääsali, 0 - numeroimattomat paikat,1,25
Pääsali, 1 - numeroimattomat paikat,1,25
```

If the user happens to get place 1 from both row 0 and 1 it will result in same program+zone+number with only differing row.

**Comment by Aketzu** [comment]
Ping @akx of [@kcsry/paikkala](https://github.com/kcsry/paikkala)

**Comment by akx** [comment]
Could be added, I guess! Sibeliustalo has seat numbers that are unique across the room, which influenced that design.

**Comment by japsu** [comment]
please reopen in https://github.com/kcsry/paikkala
