### ISSUE TITLE
Out of the box format-on-save in VS Code for Python and Typescript

### ISSUE THREAD

**Issue by japsu** [con2/kompassi#319]
Japsu would like all contributors to automatically format their Python code with Black (with configuration from `kompassi:pyproject.toml`) and TypeScript code with Prettier (with configuration from `kompassi2:package.json`).

Japsu has configured his own VS Code as follows:

```json
  "[python]": {
    "editor.tabSize": 4,
    "editor.formatOnSave": true,
    "editor.formatOnType": true,
    "editor.defaultFormatter": "ms-python.black-formatter"
  },
  "[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.formatOnSave": true,
    "editor.formatOnType": true
  },
  "[typescriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.formatOnSave": true,
    "editor.formatOnType": true
  },
```

Unknown if This Is The Way(TM) to do this in 2024. @akx @hannesj please comment and suggest embetterance.

Document it [here](https://outline.con2.fi/doc/coding-conventions-3BQSDK5WpC).

**Comment by akx** [comment]
In general: I would recommend [the Ruff formatter](https://docs.astral.sh/ruff/formatter). (It The [VSCode integration docs](https://marketplace.visualstudio.com/items?itemName=charliermarsh.ruff) say the magic words then are

```json
{
  "[python]": {
    "editor.formatOnSave": true,
    "editor.defaultFormatter": "charliermarsh.ruff"
  }
}
```

**Comment by japsu** [comment]
@akx thanks for the tip! I'm open to trying it out. How about `ruff lint`, is it any good?

**Comment by akx** [comment]
The linter is pretty awesome, yep!

**Comment by japsu** [comment]
https://github.com/con2/kompassi/commit/bca30f9dcdb9f54d3087388958a7f547406abde7 kompassi (Python) side done, next up is kompassi2 (TypeScript)

**Comment by Hilzu** [comment]
I think this is done now?
