### ISSUE TITLE
When a survey has closed, the survey list still shows "Opening at TIME"

### ISSUE THREAD

**Issue by japsu** [con2/kompassi#458]
Case in point https://v2.kompassi.eu/events/tracon2024/surveys/artisan-application

![Image](https://github.com/con2/kompassi/assets/109397/33ac345f-e14a-4e0f-b4c2-edf98b87f4a6)

![Image](https://github.com/con2/kompassi/assets/109397/fee800a7-0020-45fb-bdea-8878bf7b3ca1)

**Comment by SwarajBaral** [comment]
I would like to take this up. Could you maybe point to where I should start @japsu ?

**Comment by japsu** [comment]
I'm sorry @SwarajBaral, we're unable to support drive-by contributions from people unknown to us at this time.

**Comment by SwarajBaral** [comment]
Ok, so it is not open for contributions from outsiders ? Or will you just not be able to support me and I can raise a PR if I manage to fix the issue ?
