### ISSUE TITLE
Dimension flags: As a program manager I want to hide a dimension from list filters or detail view

### ISSUE THREAD

**Issue by japsu** [con2/kompassi#475]
Related to #474

Once we implement freeform location, it won't make sense any more to show in the program detail view the location both as dimension bubble and freeform location.

Propose adding flags such as `isListFilter` (default `true`) and `isShownInDetail` (default `true`) so that `special` dimensions such as `date` and `room` may be hidden in specific contexts.

An alternative would be to base this on `locationDimension`, but that would be too magical.

[Slack discussion](https://con2.slack.com/archives/C3ZGNGY48/p1713108274937129)

**Comment by knomepasi** [comment]
`showWithDimensionTitle`: True if the dimension values need to be presented with the dimension title to be understandable

**Comment by japsu** [comment]
NB `isShownWithDimensionTitle` https://outline.con2.fi/doc/general-conventions-JEpkPTjKUz#h-boolean-prefixes-are-preferred-but-not-mandatory

**Comment by knomepasi** [comment]
`isNegativeSelectionFilter`: True if the selection needs to be negative
Use case: Accessibility flags (nobody wants to specifically join program with specific accessibility issues)
